// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riukwcgnaghvxaqeujmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdWt3Y2duYWdodnhhcWV1am1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzU1NjksImV4cCI6MjA3MDY1MTU2OX0.5CO1eEo0mnDrsoxURXVWU5JtE33L8RmaAgcNW9c2e04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});